---

- hosts: freenas
  roles:
    - jails_setup

- hosts: jails
  roles:
    - pre_setup
    - mdns
    - user_customization
  tags: [all]

- hosts: media
  roles: [media_group]
  tags: [media]

- hosts: reverse-proxy
  roles: [reverse_proxy]
  tags: [app]

- hosts: rtorrent
  roles: [rtorrent]
  tags: [app]

- hosts: sabnzbd
  roles: [sabnzbd]
  tags: [app]

- hosts: plex
  roles: [plex]
  tags: [app]

- hosts: sonarr
  roles: [sonarr]
  tags: [app]

- hosts: dnscrypt-proxy
  roles: [dnscrypt-proxy]
  tags: [app]

- hosts: stats
  roles: [stats]
  tags: [app]
