---
all:
  hosts:
    freenas:
      ansible_ssh_host: freenas.local
      ansible_python_interpreter: /usr/local/bin/python3
  children:
    jails:
      hosts:
        reverse-proxy:
          ansible_ssh_host: reverse-proxy.local
          ansible_python_interpreter: /usr/local/bin/python3
        rtorrent:
          ansible_ssh_host: rtorrent.local
          ansible_python_interpreter: /usr/local/bin/python3
        sabnzbd:
          ansible_ssh_host: sabnzbd.local
          ansible_python_interpreter: /usr/local/bin/python3
        plex:
          ansible_ssh_host: plex.local
          ansible_python_interpreter: /usr/local/bin/python3
        sonarr:
          ansible_ssh_host: sonarr.local
          ansible_python_interpreter: /usr/local/bin/python3
        radarr:
          ansible_ssh_host: radarr.local
          ansible_python_interpreter: /usr/local/bin/python3
        dnscrypt-proxy:
          ansible_ssh_host: dnscrypt-proxy.local
          ansible_python_interpreter: /usr/local/bin/python3
        stats:
          ansible_ssh_host: stats.local
          ansible_python_interpreter: /usr/local/bin/python3
    media:
      hosts:
        rtorrent:
        sabnzbd:
        plex:
        sonarr:
        radarr:
